name: Yarn Workflow
on:
  push:
    path:
      - 'resources/js/*'
jobs:
  build:
    name: Yarn build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn run production
